### ISSUE TITLE
Init from String?

### ISSUE THREAD

**Issue by agordeev** [sdq/rrule.swift#2]
Thanks for a great lib! Are there any plans to initialize a rule from string like `"RRULE:FREQ=MONTHLY;DTSTART=20160404T021000Z;COUNT=5;INTERVAL=2;WKST=MO;BYDAY=MO,TU"` ?

I used https://github.com/teambition/RRuleSwift, but unfortunately it uses JS bridging and not thread safe. This lib looks much better

**Comment by sdq** [comment]
Nope, I think it's easy to parse the parameters from the string by developers 😄 

Thanks for your attention
